### ISSUE TITLE
trimap

### ISSUE THREAD

**Issue by 2409950175** [np-csu/AlphaMatting#4]
Hello, thanks for code! I get a problem, hou can i get my image's trimap? Thanks a lot.

**Comment by BrainPotter** [comment]
> Hello, thanks for code! I get a problem, hou can i get my image's trimap? Thanks a lot.

Can this program ran well on win10？

**Comment by 2409950175** [comment]
I could run this program on win7,  but i have not try it on win10.

**Comment by 2409950175** [comment]
> > Hello, thanks for code! I get a problem, hou can i get my image's trimap? Thanks a lot.
> 
> Can this program ran well on win10？

I could run this program on win7, but i have not try it on win10.

**Comment by cenwfohdkue** [comment]
> Hello, thanks for code! I get a problem, hou can i get my image's trimap? Thanks a lot.

Do you Know how to load Trimap now ? Sincerely look for your help. Thanks.

**Comment by 2409950175** [comment]
> > Hello, thanks for code! I get a problem, hou can i get my image's trimap? Thanks a lot.
> 
> Do you Know how to load Trimap now ? Sincerely look for your help. Thanks.

Hello! I get my image's trimap accroding to https://github.com/lnugraha/trimap_generator, you can try it. I hope it can help you.

**Comment by cenwfohdkue** [comment]
> > > Hello, thanks for code! I get a problem, hou can i get my image's trimap? Thanks a lot.
> > 
> > 
> > Do you Know how to load Trimap now ? Sincerely look for your help. Thanks.
> 
> Hello! I get my image's trimap accroding to https://github.com/lnugraha/trimap_generator, you can try it. I hope it can help you.

Thanks! Got it.
